server:
  port: 9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb://ixml:1234@mongodb-user:27019/CLASS-DB?authSource=admin

  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: http://localhost:8080/realms/school-flow-realm
          jwk-set-url: ${spring.security.oauth2.resourceServer.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  oauth2:
    resource-id: utopis-client
    principal-attribute: preferred_name